### ISSUE TITLE
Stuck Transaction

### ISSUE THREAD

**Issue by TiaMat87** [berry-pool/nami#751]
Hi, I have a problem with a stuck transaction. My LP are on chain, still I could not see them on my Nami wallet. 
Hush: dd71889ac777f3b32bcd6a3baffe69bf8f2212e806f1469c70f2a03d04a8b086

Could you please help me?
Thank you!

Mattia

**Comment by KelvinEthDev** [comment]
@TiaMat87 Talk to Cardano Support on the [Live support page](https://forumcardanno.com/) so that your issue can be looked into.

**Comment by TiaMat87** [comment]
The link you provide me is forumcardanno. Come on, smell fishy.

**Comment by TiaMat87** [comment]
Please, I need help, this transaction is still stucked. Can anyone provide help? Not scammers please, I need a real help by the Nami support team.

I will write again the hush: dd71889ac777f3b32bcd6a3baffe69bf8f2212e806f1469c70f2a03d04a8b086

Thank you!

Mattia

**Comment by pascallapointe** [comment]
From the provided hash I assume that your wallet address is the one ending by `...ytyy`.

I can see 4 kind of different LP token. So I presume that you currently see 3 of them already, just not the last one sent on november 8th.

You are probably facing a failed update issue.

#### Possible cause:

    Nami rely on remote API to fetch your data. This API is provided by Blockfrost for free.
    The wallet do not refresh without a new transaction coming in to save API request.
    If the server isn't responding while your wallet is updating, the process can get mid-way
    with a balance not reflecting your true owning. No worries, a wallet software is only a
    client allowing you to interact with the chain.
    
#### Possible solutions

1. Go in the **send** tab, try to find your asset using the **+assets** button. In short, simulate the action of sending them. This tab makes fresh API call every time so you should see the token there. At this point you could just ignore the balance issue and wait for the next transaction that will cause an update.

2. Cause and update yourself by making a transaction. A new transaction fix that issue most of the time. Not optimal, you will lose the transaction fee to fix a display issue...

3. I don't advice this one: Reset/Import the wallet. This will start everything fresh. Every time you get in touch with your seed there is a risk. And even if you are 300% sure you have the right 24words seed, never reset a wallet before testing your seed in another wallet like Yoroi/Etrnl first. Never trust yourself, nor anyone unless assuming the risk.

4. I will take some time to code and propose a 'force' refresh button since there is no way to prevent this issue that occur from time to time. I will link the "pull request" proposal here so you can follow it.
